# Use an official Node.js runtime as a parent image
FROM node:14 AS build

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Build the application for production
RUN npm run build

# Start a new stage to serve the app
FROM nginx:alpine

# Copy the build output to the nginx html directory
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run Nginx
CMD ["nginx", "-g", "daemon off;"]

